const fs = require('fs');
let c = fs.readFileSync('scripts/generate-blogs.mjs', 'utf8');

const toolsCode = [
  '{ cat: "Tools", name: "Text Case Converter", items: ["Text Case Converter"] }',
  '{ cat: "Tools", name: "Word Counter", items: ["Word Counter"] }',
  '{ cat: "Tools", name: "CSV to JSON", items: ["CSV to JSON"] }',
  '{ cat: "Tools", name: "JSON to CSV", items: ["JSON to CSV"] }',
  '{ cat: "Tools", name: "Base64 Encoder", items: ["Base64 Encoder"] }',
  '{ cat: "Tools", name: "Base64 Decoder", items: ["Base64 Decoder"] }',
  '{ cat: "Tools", name: "URL Encoder", items: ["URL Encoder"] }',
  '{ cat: "Tools", name: "URL Decoder", items: ["URL Decoder"] }',
  '{ cat: "Tools", name: "HTML Entity Encoder", items: ["HTML Entity Encoder"] }',
  '{ cat: "Tools", name: "HTML Entity Decoder", items: ["HTML Entity Decoder"] }',
  '{ cat: "Tools", name: "Binary to Text", items: ["Binary to Text"] }',
  '{ cat: "Tools", name: "Text to Binary", items: ["Text to Binary"] }',
  '{ cat: "Tools", name: "Hex to Text", items: ["Hex to Text"] }',
  '{ cat: "Tools", name: "Text to Hex", items: ["Text to Hex"] }',
  '{ cat: "Tools", name: "ASCII to Text", items: ["ASCII to Text"] }',
  '{ cat: "Tools", name: "Text to ASCII", items: ["Text to ASCII"] }',
  '{ cat: "Tools", name: "Rot13 Encoder", items: ["Rot13 Encoder"] }',
  '{ cat: "Tools", name: "Decimal to Binary", items: ["Decimal to Binary"] }',
  '{ cat: "Tools", name: "Decimal to Hex", items: ["Decimal to Hex"] }',
  '{ cat: "Tools", name: "Simple Calculator", items: ["Simple Calculator"] }',
  '{ cat: "Tools", name: "BMI Calculator", items: ["BMI Calculator"] }',
  '{ cat: "Tools", name: "Percentage Calculator", items: ["Percentage Calculator"] }',
  '{ cat: "Tools", name: "UUID Generator", items: ["UUID Generator"] }',
  '{ cat: "Tools", name: "Lorem Ipsum", items: ["Lorem Ipsum"] }',
  '{ cat: "Tools", name: "Password Generator", items: ["Password Generator"] }',
  '{ cat: "Tools", name: "Timestamp Converter", items: ["Timestamp Converter"] }',
  '{ cat: "Tools", name: "Hex to RGB", items: ["Hex to RGB"] }',
  '{ cat: "Tools", name: "RGB to Hex", items: ["RGB to Hex"] }',
  '{ cat: "Tools", name: "String Reverser", items: ["String Reverser"] }',
  '{ cat: "Tools", name: "Remove Duplicate Lines", items: ["Remove Duplicate Lines"] }',
  '{ cat: "Tools", name: "Sort Lines", items: ["Sort Lines"] }',
  '{ cat: "Tools", name: "Line Counter", items: ["Line Counter"] }',
  '{ cat: "Tools", name: "SHA256 Hash", items: ["SHA256 Hash"] }',
  '{ cat: "Tools", name: "SHA512 Hash", items: ["SHA512 Hash"] }',
  '{ cat: "Tools", name: "Text Diff", items: ["Text Diff"] }',
  '{ cat: "Tools", name: "URL Parser", items: ["URL Parser"] }',
  '{ cat: "Tools", name: "CSS Minifier", items: ["CSS Minifier"] }',
  '{ cat: "Tools", name: "Random Number", items: ["Random Number"] }',
  '{ cat: "Tools", name: "JSON Formatter", items: ["JSON Formatter"] }',
  '{ cat: "Tools", name: "JSON Minifier", items: ["JSON Minifier"] }',
  '{ cat: "Tools", name: "Markdown to HTML", items: ["Markdown to HTML"] }',
  '{ cat: "Tools", name: "HTML to Markdown", items: ["HTML to Markdown"] }',
  '{ cat: "Tools", name: "MD5 Hash Generator", items: ["MD5 Hash Generator"] }',
  '{ cat: "Tools", name: "Color Palette Extractor", items: ["Color Palette Extractor"] }',
  '{ cat: "Tools", name: "CSS Gradient Generator", items: ["CSS Gradient Generator"] }',
  '{ cat: "Tools", name: "Border Radius Generator", items: ["Border Radius Generator"] }',
  '{ cat: "Tools", name: "Box Shadow Generator", items: ["Box Shadow Generator"] }',
  '{ cat: "Tools", name: "Text Shadow Generator", items: ["Text Shadow Generator"] }',
  '{ cat: "Tools", name: "SQL Formatter", items: ["SQL Formatter"] }',
  '{ cat: "Tools", name: "XML Formatter", items: ["XML Formatter"] }',
  '{ cat: "Tools", name: "YAML to JSON", items: ["YAML to JSON"] }',
  '{ cat: "Tools", name: "JSON to YAML", items: ["JSON to YAML"] }',
  '{ cat: "Tools", name: "JWT Decoder", items: ["JWT Decoder"] }',
  '{ cat: "Tools", name: "QRCode Generator", items: ["QRCode Generator"] }',
  '{ cat: "Tools", name: "Barcode Generator", items: ["Barcode Generator"] }',
  '{ cat: "Tools", name: "Image to Base64", items: ["Image to Base64"] }',
  '{ cat: "Tools", name: "Base64 to Image", items: ["Base64 to Image"] }',
  '{ cat: "Tools", name: "SVG Optimizer", items: ["SVG Optimizer"] }',
  '{ cat: "Tools", name: "Favicon Generator", items: ["Favicon Generator"] }',
  '{ cat: "Tools", name: "Meta Tag Generator", items: ["Meta Tag Generator"] }',
  '{ cat: "Tools", name: "Robots Txt Generator", items: ["Robots Txt Generator"] }',
  '{ cat: "Tools", name: "Htaccess Generator", items: ["Htaccess Generator"] }',
  '{ cat: "Tools", name: "Sitemap Generator", items: ["Sitemap Generator"] }',
  '{ cat: "Tools", name: "Schema Markup Generator", items: ["Schema Markup Generator"] }',
  '{ cat: "Tools", name: "Open Graph Generator", items: ["Open Graph Generator"] }',
  '{ cat: "Tools", name: "Twitter Card Generator", items: ["Twitter Card Generator"] }',
  '{ cat: "Tools", name: "UTM Builder", items: ["UTM Builder"] }',
  '{ cat: "Tools", name: "Email Extractor", items: ["Email Extractor"] }'
].join(',\n');

c = c.replace('const topics = [', 'const topics = [\n' + toolsCode + ',');

fs.writeFileSync('scripts/generate-blogs.mjs', c);
